export * from './products.actions';
export * from './product.actions';
export * from './securityandprivacy.actions';
export * from './account.actions';
export * from './contact.actions';
export * from './contacts.actions';
export * from './discount.actions';
export * from './discounts.actions';
export * from './service.actions';
export * from './services.actions';
export * from './user.actions';
export * from './users.actions';
// export * from './doctors.actions';
// export * from './doctor.actions';
