name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
      
    - name: Install dependencies
      working-directory: client
      run: yarn install
      
    - name: Build client
      working-directory: client
      run: yarn run build
      
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.4.0
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
        export_default_credentials: true

      
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0.4.2
      with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}
      
    - name: Configure Docker to use Google Cloud Container Registry
      run: gcloud auth configure-docker
      
    - name: Build and Deploy to Cloud Run
      run: |
        gcloud run deploy coopercrown240523 --source --platform managed --region us-east1
